dana/urls.py
from . import views
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'dana'
urlpatterns = [
    path('', req, name='req'),
    path('add_request/', add_request, name='add_request'),
    path('rq_delete/<id>', views.rq_delete, name='rq_delete')
]

tk1_new/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rara.urls')),
    path('index/', include('index.urls')),
    path('review/', include('review.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
]

dana/models.py
from django.db import models
import datetime

# Create your models here.

#RATE=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
RANGE =[('100-300 M','100-300 M'),('301-500 M','301-500 M'),('501-1000 M','501-1000 M'),('1001-2000 M','1001-2000 M'),('2001++ M','2001++ M')]

class Request(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    wideScale = models.CharField(max_length=50)
    budget = models.CharField(max_length=50, choices=RANGE)
    detail = models.TextField()

dana/forms.py
from django import forms
from .models import Request
from django.forms import ModelForm

class RequestForm(ModelForm):
    class Meta:
        model= Request
        fields = ['name', 'email', 'wideScale', 'budget','detail']
        labels = {'name': 'Name','email':'Email', 'wideScale':'Wide-Scale', 'budget':'Budget', 'detail':'Detail'}
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s your name?'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'email',
                                        'placeholder' : 'What\'s your email?'}),
            'wideScale' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'How big is the Area? (ex : 100 m2)'}),                           
            'budget' : forms.Select(attrs={'class': 'form-control'}),
            'detail' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3', 'placeholder' : 'Describe your own dream house here'}),
        }

dana/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import RequestForm
from .models import Request
from steven.models import Contractor
import datetime

def req(request):
	data = Contractor.objects.all()
	form = RequestForm(request.POST)
	content = {'form' : form, 'data' : data}
	return render(request, 'request.html', content)

def add_request(request):
	if request.method == 'POST':
		form = RequestForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/request/')
	else:
		return redirect('/request/')


def rq_delete(request, id):
    rq = Contractor.objects.filter(id=id)
    rq.delete()
    return redirect('dana:req')

dana/templates/request.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Request Page
{% endblock %}



{% block content%}
<style>
	body{background :#6cc8a3
	}

</style>
<div class= "rev-container" style="font-family: 'Varela Round', sans-serif; color: black;">
	<br><br><br>
	<div class="form-request">
		<div class="row">
			<div class = "col sm-2">
				<img src="{% static 'img/kiri.png' %}" style="max-width:100%; height: auto">
			</div>
			<div class="col-sm-8" style="padding: 20px 20px 20px 50px">
				<p style="text-align : center; font-size: 30px"><b>Please <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> fill</span> the form to </b></p>
				<p style="text-align : center; font-size: 30px;"><b>to make a <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> Request</span> </b></p>
				<p style="text-align : center">Hi! if you want to build your dream house but you don't know who will build it for you, just fill this forms bellow</p>
			</div>
			<div class = "col sm-2">
				<img src="{% static 'img/kanan.png' %}" style="max-width:80%; height: auto">
			</div>




				<div class="col-sm-12">
					<div class="row" >
						<div class="col-sm-6" style="padding: 20px 20px 20px 50px">
							<form method="POST" action="{% url 'dana:add_request' %}">
							{% csrf_token %}
							<div class="form-group row">
						    <label for="name" class="col-sm-2 col-form-label">{{ form.name.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.name }}
						    </div>
						  </div>

							<div class="form-group row">
						    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.email.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.email }}
						    </div>
						  </div>
						</div>

						<div class="col-sm-6" style="padding: 20px 20px 20px 50px">
							<div class="form-group row">
						    <label for="wideScale" class="col-sm-2 col-form-label">{{ form.wideScale.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.wideScale }}
						    </div>
						  </div>

							<div class="form-group row">
						    <label for="budget" class="col-sm-2 col-form-label">{{ form.budget.label_tag }}</label>
						    <div class="col-sm-10">
						      {{ form.budget }}
						    </div>
						  </div>

						</div>

						</div>

						<div class="form-group" style="padding-left: 35px">
					    	<label for="exampleFormControlTextarea1">{{ form.detail.label_tag }}</label><br>
					    	<small>Describe your own dream house in detail to make contractor easy to design it for you. If you have some trouble just send message to us</small>
							{{ form.detail }}
							
					  	</div>

						<div class="form-group row">
					    <div class="col-sm-6 offset-6 center">
					      <button type="submit" class="btn btn-primary">Submit</button>
							</div>
					  </div>

				</div>

				</form>
			</div>
		<hr style="border: 2px solid white; margin-right: 50px; margin-left: 50px">

		<div class="list-group" style="padding: 40px 100px 30px 100px">
        	 <p style="color: white; font-family:'Varela Round', sans-serif; font-size: 30px"><b><span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Projects</span> Done</b></p>
        	{% for db in data %}
        		<div style="background-color: #ffafaf; padding: 30px; word-wrap : break-word">
			  		<h4 class="mb-1"><b>{{ db.name }}</b></h4>
			  		<small class="text-muted">{{ db.date }}</small>
						<p class="mb-1">{{ db.email }}</p>
						<p class="mb-1">{{ db.project }}</p>
						<p class="mb-1">{{ db.link }}</p>
			  		<p class="mb-1">{{ db.detail }}</p>
						<div class="offset-10 center">
							<a href="{% url 'dana:rq_delete' id=db.id %}" class="btn btn-primary"><button>Delete</button></a>
						</div>
		  		</div>
					<!-- kjdkwkjd -->
		  		<br>
		  	{% endfor %}
		</div>
	</div>
	<br>
	<br>
</div>
{% endblock %}