dana/urls.py
from . import views
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'dana'
urlpatterns = [
    path('', req, name='req'),
    path('add_request/', add_request, name='add_request'),
    path('rq_delete/<id>', views.rq_delete, name='rq_delete')
]

review/urls.py
from .views import *
from django.shortcuts import render
from django.urls import path

app_name = 'review'
urlpatterns = [
    path('', rev, name='rev'),
    path('add_review/', add_review, name='add_review')
]

tk1_new/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rara.urls')),
    path('index/', include('index.urls')),
    path('review/', include('review.urls')),
    path('contractor/', include('steven.urls')),
    path('request/', include('dana.urls')),
]

review/models.py
from django.db import models
import datetime

# Create your models here.

RATE=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]

class Review(models.Model):
	date = models.DateTimeField(auto_now_add=True)
	name = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	rate = models.CharField(max_length=50, choices=RATE)
	comment = models.TextField()

review/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm

class ReviewForm(ModelForm):
    class Meta:
        model= Review
        fields = ['name', 'email', 'rate', 'comment']
        labels = {
            'name': 'Name','email':'Email', 'rate':'Rate', 'comment':'Comment',
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'text',
                                        'placeholder' : 'What\'s your name?'}),
            'email' : forms.TextInput(attrs={'class': 'form-control',
                                        'type' : 'email',
                                        'placeholder' : 'What\'s your email?'}),
            'rate' : forms.Select(attrs={'class': 'form-control'}),
            'comment' : forms.Textarea(attrs={'class': 'form-control',
                                        'type' : 'textarea', 'rows' : '3'}),
        }

review/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ReviewForm
from .models import Review
import datetime

def rev(request):
	data = Review.objects.all()
	form = ReviewForm(request.POST)
	content = {'form' : form, 'data' : data}
	return render(request, 'review.html', content)

def add_review(request):
	if request.method == 'POST':
		form = ReviewForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/review/')
	else:
		return redirect('/review/')

review/templates/review.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Review Page
{% endblock %}



{% block content%}
<div class= "rev-container">
	<br><br><br>
	<div class="form-review">
		<div class="row">
		    <div class="col-sm-8" style="padding: 20px 20px 20px 50px">
		    	<p style="font-size: 25px"><b>Please help us to provide you a <span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)"> better service </span> </b></p>
		    	<form method="POST" action="{% url 'review:add_review' %}">
					{% csrf_token %}
				  <div class="form-group row">
				    <label for="name" class="col-sm-2 col-form-label">{{ form.name.label_tag }}</label>
				    <div class="col-sm-10">
				      {{ form.name }}
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="inputEmail3" class="col-sm-2 col-form-label">{{ form.email.label_tag }}</label>
				    <div class="col-sm-10">
				      {{ form.email }}
				    </div>
				  </div>
				  <div class="form-group row">
				    <label for="rate" class="col-sm-2 col-form-label">{{ form.rate.label_tag }}</label>
				    <div class="col-sm-10">
				      {{ form.rate }}
				    </div>
				  </div>

				  <div class="form-group">
				    <label for="exampleFormControlTextarea1">{{ form.comment.label_tag }}</label>
				    {{ form.comment }}
				  </div>
				  <div class="form-group row">
				    <div class="col-sm-10">
				      <button type="submit" class="btn btn-primary">Submit</button>
				    </div>
				  </div>
				</form>
		    </div>
		    <div class="col-sm-4">
		    <img src="{% static 'img/popup.png' %}" style="max-width:100%; height: auto">
			</div>
		</div>
		<hr style="border: 2px solid white; margin-right: 50px; margin-left: 50px">

		<div class="list-group" style="padding: 4% 10% 3% 10%">
        	 <p style="color: white; font-family:'Varela Round', sans-serif; font-size: 30px"><b><span style="color:  #fe5b46; background-color: rgba(255,255,255,0.5)">Thought</span> on Us</b></p>
        	{% for db in data %}
        		<div style="background-color: #ffafaf; padding: 30px">
			  		<h4 class="mb-1"><b>{{ db.name }}</b></h4>
			  		<div class="d-flex w-100 justify-content-between">
			  			<p class="mb-1">{{ db.rate }}/5</p>
			  			<small class="text-muted">{{ db.date }}</small>
			  		</div>
			  		<p class="mb-1">{{ db.comment }}</p>
		  		</div>
		  		<br>
		  	{% endfor %}
		</div>
	</div>
	<br>
	<br>
</div>
{% endblock %}